### ISSUE TITLE
ItemPhysic Full is not compatible with Mr_Crayfish's Obfuscate

### ISSUE THREAD

**Issue by DR01D-Qs** [CreativeMD/ItemPhysic#81] opened 2019-04-06 11:36 UTC
There are no crashes or something like that, but when both of these mods are installed, the server side of the mod works fine, but the client side (renderer) doesn't, so that dropped items look vanilla. No matter what graphics settings are you on, all items look like vanilla fancy.

Built a large modpack with ~180 mods and had to manually look for the conflicting one, that was fun...

**Comment by CreativeMD** [comment] 2019-04-09 17:06
Ok, looks like somebody else has reported it as well: https://minecraft.curseforge.com/projects/obfuscate/issues/12 I have no idea how to fix it, I will try to contact Mr Crayfish.

**Comment by SeanChengN** [comment] 2019-05-14 06:25
Well, I just found this problem, I tested hundreds of mods too...😩
@MrCrayfish Could you please check this out?

**Comment by stonemandave** [comment] 2019-12-17 16:04
I just found out about this so there hasn't been any progress so it's one or the other.

**Comment by CreativeMD** [comment] 2019-12-17 16:11
Nope I can't do anything until @MrCrayfish responds.

**Comment by stonemandave** [comment] 2019-12-17 16:37
I post on his also but thanks for being an active member to the community it's just the life of modding

**Comment by Dimitry-Blitzbrieg** [comment] 2020-03-03 03:30
suffering from the issue as well... Has there been any update to whether or not @MrCrayfish has responded?

**Comment by CreativeMD** [comment] 2020-03-03 09:52
Sorry, he never responded.

**Comment by Leejit** [comment] 2020-03-25 04:47
this is crazy... I had this issue when trying to assemble my own modpack. 
but I do have a server/client pack where these are working together.
maybe you could inspect the difference between how it works on my server, and how it doesn't for most people. because I feel this is very special case scenario that it's working for me.

Obfuscate & Vehicles installed. ItemPhysic & CreativeCore installed. everything working as expected.

I can be contacted on discord Leejit#5709

**Comment by MrCrayfish** [comment] 2020-03-25 06:16
I will work towards compatability soon!

**Comment by mxnmnm** [comment] 2020-07-16 00:24
Looks like the issue is with quark's item flashing... I tested it and whenever it's disabled it breaks item physics when vehicles/obfuscate is installed.

**Comment by mxnmnm** [comment] 2020-07-16 00:37
To clarify this is on 1.12, the last time I checked 1.15 and above was broken with just the two mods installed although that may have changed (I don't follow 1.15+ development very closely because I'm still primarily using 1.12)

**Comment by Dimitry-Blitzbrieg** [comment] 2020-07-16 15:59
Yea i use 1.12 as well. Its a fiasco trying to make a personal modpack on newer versions due to bugs and incompatibilities, i bet its a pain for developers for a mod to work with future versions of the game, though i don't do any mod development myself i would just be guessing here. Anyway devs! Let me know how hard it is to port your mods to a new version of minecraft and what you have to go though. I'm. Quite curious now.

Anyways going back to this bug has there been any fixes made? Have not been with the minecraft community in a while and have not played with my mod packs yet to test any changes. I'm still guessing the incompatibility with obfuscate is still a thing.

**Comment by mxnmnm** [comment] 2020-07-16 20:15
It seems to work in my large modpack so maybe another mod I have fixes it (if it still occurs with just the two which it probably does) What I do know is that turning off item flashing when despawning in quark breaks it.

**Comment by CreativeMD** [comment] 2020-10-06 09:47
I don't think this issue will ever be fixed for 1.12, it's already fixed for 1.16. So I will close it.

**Closed as completed by CreativeMD** 2020-10-06 09:47 UTC
