### ISSUE TITLE
Config doesn't change

### ISSUE THREAD

**Issue by Flusterated** [CreativeMD/ItemPhysic#201] opened 2024-06-30 16:43 UTC
Everytime I edit the config ingame using "/cmdconfig" and click "save" nothing changes. I am trying to disable auto-pickup and enable a custom key pickup. 

I am using Modrinth modloader with Fabulously Optimized modpack.

**Comment by CreativeMD** [comment] 2024-07-01 20:44
What minecraft version? What version of CreativeCore and ItemPhysic? What setting are you changing? Are you on a server or singleplayer?

**Comment by Flusterated** [comment] 2024-07-02 08:47
Minecraft:   1.20.4
ItemPhysic:   1.7.1
Creative Core:   2.11.26
Singleplayer

I type /cmdconfig, and I change to AutoPickup to false and then "save". After clicking save nothing happens and the config goes back to the default settings.

All I want is to disable auto pickup and use a key-bind to pickup items.

**Comment by CreativeMD** [comment] 2024-07-02 08:53
There is no option AutoPickup. There is an option in /cmdconfig -> itemphysic -> pickup -> custom pickup, which you have to set to true.

**Comment by Flusterated** [comment] 2024-07-02 12:55
Thats what I meant. It wont let me change it to true.

**Comment by CreativeMD** [comment] 2024-07-02 13:00
You set it to true and it goes back to false when you open it again even though you clicked save?

**Comment by Flusterated** [comment] 2024-07-02 13:26
Yes

**Comment by CreativeMD** [comment] 2024-07-09 11:08
Hm, I cannot reproduce this issue. Is it possible for you to switch Minecraft versions? Best would be 1.21.

**Comment by FilipKompaniets3** [comment] 2024-08-13 05:17
It seems to me that you are changing the configuration during the game, but you need to do it in the main menu. When I changed the configuration during the game, it did not save. But I am not sure that this is your problem.

**Comment by CreativeMD** [comment] 2024-08-13 09:28
@FilipKompaniets3 the configuration in the main menu is the client side configuration. Ingame you can change the server settings too using the command /cmdconfig. Both client and server settings should be configurable ingame. Outside of this I never heard that it does not save. I'm very much confused by this. But 1.20.4 is not a version I really support. My focus is on 1.21 at the moment. If you can reproduce this issue I would be happy to get more information from you. Maybe a log file, maybe there is an error.

**Comment by CreativeMD** [comment] 2024-09-10 07:43
Will close this issue for now. If the issue persists in 1.21 please respond here.

**Closed as completed by CreativeMD** 2024-09-10 07:43 UTC
