### ISSUE TITLE
ItemPhysic Full causing java.lang.IllegalArgumentException: Start element is larger than end element

### ISSUE THREAD

**Issue by CsiPA0723** [CreativeMD/ItemPhysic#191] opened 2024-02-26 23:38 UTC
### Description

When joining a dedicated server with these mods (listed in the crash log), the server usually deadlocks or crashes. It does not always happen instantly, it can be after some time, or someone goes for a little adventure and the whole server just stops. It's still maybe not ItemPhysic's fault completely though after removing it from the server the deadlocks/crashes stopped happening.

[Minecraft Forum link](https://www.minecraftforum.net/forums/support/server-support-and/3195620-mysterious-ticking-entity-crash-server-deadlock)

### Crash Report

[crash-2024-02-11_18.40.20-server.txt](https://github.com/CreativeMD/ItemPhysic/files/14412376/crash-2024-02-11_18.40.20-server.txt)

### Mod Version

- 1.7.0

### Minecraft Version

- 1.20.1

### Forge Version

- 47.2.20

**Comment by CreativeMD** [comment] 2024-03-14 08:29
Hey, sorry for not responding earlier. I don't think this issue is connected to ItemPhysic, because this has nothing to do with it. At least the crash-report does not suggest anything. Maybe the mod Canary is involved, but even that is not sure. Sorry, but I don't see a way to help out here. Maybe there are some other errors in the log?

**Comment by briarss** [comment] 2024-04-04 17:51
I can also attest to the fact itemphysic full causes this - supposedly its to do with entities being far too high/low in the world, and is a vanilla bug: https://bugs.mojang.com/browse/MC-218504
could be items falling in unloaded chunks or something?

**Comment by CreativeMD** [comment] 2024-04-16 17:01
Maybe items can teleported far away? But I don't see what itemphysic changes about it. Would be interesting to know what kind of mods you have installed @amoooooo. Maybe this issue appears with a certain combination of mods?

**Comment by woodenscalpel** [comment] 2024-08-15 05:02
I get a similar crash when attempting to push a custom entity from my own mod with a piston.

My crash is caused by an entity collision with a piston, this crash is caused by an entity collision, and the vanilla bug posted above is caused by collision with the world border.

What seems to be happening is, in the vanilla entity collision code, EntitySectionStorage is being called with a bounding box from -MAXINT to MAXINT. Then a method (forEachAccessibleNonEmptySection) attempts to made the boundingbox  slightly bigger, by decreasing the minimum bounds and increasing the maximum bounds. This causes an overflow/underflow which ultimately causes the crash.

I am not yet sure what interaction is causing the vanilla entity collision code to return such a large bounding box for seemingly no reason, but I don't think it is technically your mod's fault. That being said, I am going to try to use a mixin to prevent this crash in my own mod.

**Comment by CreativeMD** [comment] 2024-08-27 12:04
@woodenscalpel thanks for your detailed response. Yeah not sure how itemphysic is related to do that. I do no change anything about this behavior. Seems like an issue which can occur if the bounding box is not set properly. It happened to me once while developing another mod. Technically it's also not a vanilla issue, but just an issue of another mod which does not cause a crash immediately. Would be good if it is reproduceable then it will be a lot easier to figure out which mod is causing it.

I will close this issue for now. If this issue occurs again for anyone feel free to report it here.

**Closed as completed by CreativeMD** 2024-08-27 12:04 UTC
