### ISSUE TITLE
Issues with optifine

### ISSUE THREAD

**Issue by Powerless001** [CreativeMD/ItemPhysic#118] opened 2020-05-08 17:40 UTC
This mod used to work with optifine but with the newest 1.15.2 beta of Optifine broke the visuals. The items still behave like they should, like floating, sinking, burning ect. But you don't see the items flip and sit flat on the ground. I know the Optifine is still in beta, but I figured I would let you know about it.

**Comment by CreativeMD** [comment] 2020-05-14 09:23
I have reported this issue to Optifine, let's hope it can be solved: https://github.com/sp614x/optifine/issues/3939

**Comment by ZekerZhayard** [comment] 2020-05-14 11:58
i suspect it is caused by cpw/modlauncher#37 , and OptiForge may fix it temporarily.

**Comment by CreativeMD** [comment] 2020-10-02 09:18
This issue should be fixed in the newest version of Optifine for 1.16.3.

**Closed as completed by CreativeMD** 2020-10-02 09:18 UTC
