### ISSUE TITLE
Items won`t drop when I press "Q" on servers.

### ISSUE THREAD

**Issue by Tunarslan** [CreativeMD/ItemPhysic#213] opened 2024-11-04 18:50 UTC
In servers, When I hit "Q" the item disappears but it doesn`t drop. The item is still actually there but it`s in a ghost state.
It reappears after a while or if I click at the slot where the item used to be.
I can still drop stuff by opening my inventory and dragging it out.
Note that I have other mods installed.

https://github.com/user-attachments/assets/403ef680-cfa4-4e01-8644-483bef041397

https://github.com/user-attachments/assets/0c954996-5fe2-4d9b-8a28-3b402f5a40a4

https://github.com/user-attachments/assets/4889bad6-1035-4f5d-aa65-450821270522

**Comment by Tunarslan** [comment] 2024-11-05 13:41
Update: Mods do not cause this and I am pretty sure it's every server, not just Cube Craft.

**Comment by CreativeMD** [comment] 2024-11-05 14:51
Do you mean other mods do not cause this or do you mean also ItemPhysic cannot be the cause?

**Comment by Tunarslan** [comment] 2024-11-09 18:05
No I removed every other mod but the bug was still there.

**Comment by CreativeMD** [comment] 2024-11-12 13:57
What server platform are you using? NeoForge?

**Comment by Gav120** [comment] 2024-11-13 02:54
Same here, I have a server with forge mods (including this mod) and when I try to drop an item with "Q" the item "disappear" and appears again in a moment, the only way to drop the item is open the inventory and throw it there.
The server host is Exaroton, the forge version is 47.3.0 in Minecraft 1.20.1 and the Item Physics mod version is 1.8.1

**Comment by CreativeMD** [comment] 2024-11-22 13:25
@Gav120 What other mods are installed? Sorry for responding that late.

**Comment by CreativeMD** [comment] 2024-12-06 14:00
I cannot reproduce this issue. Maybe try out the newest version and see if it is fixed. I will close this issue for now. You can still respond here. I just need more information, a log file for example would greatly help.

**Closed as completed by CreativeMD** 2024-12-06 14:00 UTC

**Comment by PluginsKers** [comment] 2025-10-06 05:42
I've successfully reproduced the issue under the following setup:

- **Server**: Folia 1.21.8-6 (clean install, no plugins)
- **Client**: Fabric 1.21.8 (latest release)
- **Mod**: *ItemPhysic* version **1.8.11** (Fabric API version **0.17.2**)

When pressing **Q** to drop an item, nothing happens—no item is dropped, and the server logs show no errors. The behavior matches what’s shown in the video: the item remains in the inventory, and the drop action appears to be silently rejected by the server.

To rule out compatibility issues, I’ve:

- Removed all other mods
- Verified the server is running without plugins
- Tried setting `throw.enabled = false` in `itemphysic.json`, but the issue persists

Currently, the only way to drop items is by manually dragging them out of the inventory. It seems like the server is blocking or ignoring the drop action triggered by the Q key.

Is there a known fix or a way to disable this behavior entirely? Any configuration workaround would be appreciated.

**Comment by CreativeMD** [comment] 2025-10-24 15:10
@PluginsKers Is ItemPhysic installed on server side? (Btw use the ingame config instead of the config file by using the command /cmdconfig).

**Comment by PluginsKers** [comment] 2025-10-25 14:47
> [@PluginsKers](https://github.com/PluginsKers)服务器端是否安装了 ItemPhysic？（顺便使用游戏内配置而不是配置文件，可以通过命令 /cmdconfig 来使用）

is that mods?
folia is a branch of paper that only accepts plugins. I don't know how to proceed next
