### ISSUE TITLE
Not showing hand and dropped items

### ISSUE THREAD

**Issue by f-denis** [CreativeMD/ItemPhysic#168] opened 2022-07-06 20:26 UTC
I have a few mods installed just to say. I didn't want to be able to throw items using ItemPhysic, so I disabled this feature in the config file through config mode (set disableThrowHUD to false). After that, I can't see my hand, I can't see block breaking particles and neither items. Nothing happens when I enable/disable anything. Is not F1 key the problem. It functions if I delete config files though.
![image](https://user-images.githubusercontent.com/108834743/177636048-87e8650e-3f8c-44dc-a81e-3be023ec8a92.png)
![2022-07-06_23 25 15](https://user-images.githubusercontent.com/108834743/177636901-9ddac0f6-2ac7-4720-abe4-cd73e3c6277b.png)

**Comment by CreativeMD** [comment] 2022-07-11 16:28
I need more information. What minecraft version is it? Forge or fabric? What other mods are installed? I could not reproduce this with neither forge nor fabric for Minecraft 1.19.

**Comment by f-denis** [comment] 2022-07-13 11:12
[image: image.png]
Minecraft version 1.18.2, forge 40.1.60
I don't know what mods I had then but now it works. It seems another mod
was the problem
lun., 11 iul. 2022, 19:29 CreativeMD ***@***.***> a scris:

**Comment by CreativeMD** [comment] 2022-07-13 11:33
Ok, I guess I call it fixed now. If it happens again just let me know.

**Closed as completed by CreativeMD** 2022-07-13 11:33 UTC
